// This file holds the list of courses a student can pick from
// when they register or edit their profile.
// Each course has an id, the id of the school that offers it,
// a short code, and the full course name.

const courseList = [
    { id: "crs-101", schoolId: "c101", code: "BSN", name: "Bachelor of Science in Nursing" },
    { id: "crs-102", schoolId: "c101", code: "MD", name: "Doctor of Medicine" },
    { id: "crs-103", schoolId: "c101", code: "BSCE", name: "Bachelor of Science in Civil Engineering" },
    { id: "crs-104", schoolId: "c101", code: "BSEE", name: "Bachelor of Science in Electrical Engineering" },
    { id: "crs-105", schoolId: "c101", code: "BSME", name: "Bachelor of Science in Mechanical Engineering" },
    { id: "crs-106", schoolId: "c101", code: "BSSE", name: "Bachelor of Science in Sanitary Engineering" },
    { id: "crs-107", schoolId: "c101", code: "BSCpE", name: "Bachelor of Science in Computer Engineering" },
    { id: "crs-108", schoolId: "c101", code: "BEED", name: "Bachelor of Elementary Education" },
    { id: "crs-109", schoolId: "c101", code: "BSED", name: "Bachelor of Secondary Education" },
    { id: "crs-110", schoolId: "c101", code: "BPED", name: "Bachelor of Physical Education" },
    { id: "crs-111", schoolId: "c101", code: "BS Criminology", name: "Bachelor of Science in Criminology" },
    { id: "crs-112", schoolId: "c101", code: "BSBA", name: "Bachelor of Science in Business Administration" },
    { id: "crs-113", schoolId: "c101", code: "BSA", name: "Bachelor of Science in Accountancy" },
    { id: "crs-114", schoolId: "c101", code: "BSAIS", name: "Bachelor of Science in Accounting Information System" },
    { id: "crs-115", schoolId: "c101", code: "BSHM", name: "Bachelor of Science in Hospitality Management" },
    { id: "crs-116", schoolId: "c101", code: "BSTM", name: "Bachelor of Science in Tourism Management" },
    { id: "crs-117", schoolId: "c101", code: "BSIT", name: "Bachelor of Science in Information Technology" },
    { id: "crs-118", schoolId: "c101", code: "BSCS", name: "Bachelor of Science in Computer Science" },
    { id: "crs-119", schoolId: "c101", code: "BS Archi", name: "Bachelor of Science in Architecture" },
    { id: "crs-120", schoolId: "c101", code: "BSSW", name: "Bachelor of Science in Social Work" },
    { id: "crs-121", schoolId: "c101", code: "BA Comm", name: "Bachelor of Arts in Communication" },
    { id: "crs-122", schoolId: "c101", code: "AB PolSci", name: "Bachelor of Arts in Political Science" },
    { id: "crs-123", schoolId: "c101", code: "BS Psych", name: "Bachelor of Science in Psychology" },
    { id: "crs-124", schoolId: "c101", code: "JD", name: "Juris Doctor" },

    { id: "crs-125", schoolId: "c102", code: "BS Agri", name: "Bachelor of Science in Agriculture" },
    { id: "crs-126", schoolId: "c102", code: "BAT", name: "Bachelor of Agricultural Technology" },
    { id: "crs-127", schoolId: "c102", code: "BSIT", name: "Bachelor of Science in Information Technology" },
    { id: "crs-128", schoolId: "c102", code: "BEED", name: "Bachelor of Elementary Education" },
    { id: "crs-129", schoolId: "c102", code: "BSED", name: "Bachelor of Secondary Education" },
    { id: "crs-130", schoolId: "c102", code: "BTLEd", name: "Bachelor of Technology and Livelihood Education" },
    { id: "crs-131", schoolId: "c102", code: "BS IndTech", name: "Bachelor of Science in Industrial Technology" },
    { id: "crs-132", schoolId: "c102", code: "BSHM", name: "Bachelor of Science in Hospitality Management" },
    { id: "crs-133", schoolId: "c102", code: "BSBA", name: "Bachelor of Science in Business Administration" },
    { id: "crs-134", schoolId: "c102", code: "BS Criminology", name: "Bachelor of Science in Criminology" },
    { id: "crs-135", schoolId: "c102", code: "BSCS", name: "Bachelor of Science in Computer Science" },
    { id: "crs-136", schoolId: "c102", code: "BSMB", name: "Bachelor of Science in Marine Biology" },

    { id: "crs-137", schoolId: "c103", code: "BSBA", name: "Bachelor of Science in Business Administration" },
    { id: "crs-138", schoolId: "c103", code: "BSA", name: "Bachelor of Science in Accountancy" },
    { id: "crs-139", schoolId: "c103", code: "BSMA", name: "Bachelor of Science in Management Accounting" },
    { id: "crs-140", schoolId: "c103", code: "BSHM", name: "Bachelor of Science in Hospitality Management" },
    { id: "crs-141", schoolId: "c103", code: "BSTM", name: "Bachelor of Science in Tourism Management" },
    { id: "crs-142", schoolId: "c103", code: "BEED", name: "Bachelor of Elementary Education" },
    { id: "crs-143", schoolId: "c103", code: "BSED", name: "Bachelor of Secondary Education" },
    { id: "crs-144", schoolId: "c103", code: "BSIT", name: "Bachelor of Science in Information Technology" },
    { id: "crs-145", schoolId: "c103", code: "BSCS", name: "Bachelor of Science in Computer Science" },
    { id: "crs-146", schoolId: "c103", code: "BS Criminology", name: "Bachelor of Science in Criminology" },
    { id: "crs-147", schoolId: "c103", code: "BA Comm", name: "Bachelor of Arts in Communication" },
    { id: "crs-148", schoolId: "c103", code: "AB PolSci", name: "Bachelor of Arts in Political Science" },

    { id: "crs-149", schoolId: "c104", code: "BSBA", name: "Bachelor of Science in Business Administration" },
    { id: "crs-150", schoolId: "c104", code: "BSOA", name: "Bachelor of Science in Office Administration" },
    { id: "crs-151", schoolId: "c104", code: "BSHM", name: "Bachelor of Science in Hospitality Management" },
    { id: "crs-152", schoolId: "c104", code: "BSTM", name: "Bachelor of Science in Tourism Management" },
    { id: "crs-153", schoolId: "c104", code: "BEED", name: "Bachelor of Elementary Education" },
    { id: "crs-154", schoolId: "c104", code: "BSED", name: "Bachelor of Secondary Education" },
    { id: "crs-155", schoolId: "c104", code: "BSIT", name: "Bachelor of Science in Information Technology" },
    { id: "crs-156", schoolId: "c104", code: "ACT", name: "Associate in Computer Technology" }
];

